Repository ilo80/msh-av-controversy, pull requests merged in 2025-06, with the labels that each got.

#1 Simplify site
  index.html
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
Labels: enhancement

#7 Increase node size in graph viewer
  src/components/ActorsGraph.tsx
  src/types/d3-force-3d.d.ts
Labels: enhancement, codex

#9 [CHLORE] Asset optimization + code cleanup + max/min zoom
  src/App.tsx
  src/assets/actor/association_consommateurs.png
  src/assets/actor/associations.svg
  src/assets/actor/chercheurs.png
  src/assets/actor/chercheurs.svg
  src/assets/actor/gouvernements.png
  src/assets/actor/gouvernements.svg
  src/assets/actor/syndicats.png
  src/assets/actor/syndicats.svg
  src/components/ActorsGraph.tsx
  src/data/actorsData.ts
  src/index.css
Labels: enhancement

#11 [FEAT] Add graph sidebar
  src/App.tsx
  src/components/ActorSidebar.tsx
  src/components/ActorsGraph.tsx
  src/components/ProgressBar.tsx
  src/data/actorsData.ts
  src/index.css
  src/models/actor/actor.ts
  src/models/graph/progress-bar.ts
Labels: enhancement

#16 [FEAT] Add sections for the main page
  src/App.tsx
  src/components/ActorSection.tsx
  src/components/Introduction.tsx
  src/components/TimelineSection.tsx
  src/data/timelineData.ts
  src/index.css
  src/models/timeline/timeline.ts
Labels: enhancement

#17 [FEAT] Resize graph
  src/components/ActorsGraph.tsx
  src/index.css
Labels: enhancement

#19 [FIX] Fix sidebar
  src/index.css
Labels: bug

#20 [FIX] Fix various bug
  src/components/ActorSection.tsx
  src/components/ActorsGraph.tsx
  src/components/Introduction.tsx
  src/components/Navbar.tsx
  src/components/TimelineSection.tsx
  src/index.css
Labels: bug

#24 [REFACTOR] Redesign footer
  src/components/Footer.tsx
Labels: enhancement

#25 [FIX] Fix footer width
  src/components/Footer.tsx
  src/index.css
Labels: bug

#30 [FIX] Fix sidebar
  src/index.css
Labels: bug

#31 [FEAT] Add missing data
  src/data/statisticsData.ts
  src/data/terminologyData.ts
  src/models/statistic/statistic.ts
  src/models/terminology/terminology.ts
Labels: enhancement

#34 [FIX] prevent burger menu from opening when hidden
  src/components/Navbar.tsx
Labels: bug

#38 CHLORE Add flexbox to stats card
  src/components/StatisticsSection.tsx
  src/index.css
Labels: enhancement

#41 |FEAT] Add sources page
  package-lock.json
  package.json
  src/components/Footer.tsx
  src/components/Navbar.tsx
  src/components/Sources.tsx
  src/index.css
  src/main.tsx
  src/pages/Sources.tsx
  src/types/react-router-hash-link.d.ts
  vercel.json
Labels: enhancement

#42 [FEAT] Add Terminology
  src/components/FlipCard.tsx
  src/components/Navbar.tsx
  src/components/Terminology.tsx
  src/data/terminologyData.ts
  src/index.css
  src/pages/Home.tsx
Labels: enhancement

#46 [UPDATE] Add moral machine link
  src/components/Introduction.tsx
  src/index.css
Labels: enhancement

#48 [FIX] Change terminology card style
  src/index.css
Labels: bug

#49 [CHLORE]: Change components order
  src/components/Navbar.tsx
  src/pages/Home.tsx
Labels: enhancement

#57 [FIX]: Fix scroll for actors
  src/components/ActorSection.tsx
Labels: bug
